config-version: 1

update-checker:
  notify-on-join: true
  check-interval: 1

modules-configs:
  broadcast:
    enabled: true
  clear-inventory:
    enabled: true
  coordinates:
    enabled: true
  cross-teleport:
    enabled: true
    sending_delay: 1
  feed:
    enabled: true
  fly:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  kill:
    enabled: true
  knockback:
    enabled: true
  lightning:
    enabled: true
  join-message:
    enabled: true
  quit-message:
    enabled: true
  plugin-list:
    enabled: true
  private-chat:
    enabled: true
  rotate:
    enabled: true
  shuffle:
    enabled: true
  spawn:
    enabled: true
    on-join: true
    on-void: true
    on-respawn: true
    location: ''
  speed:
    enabled: true
  sudo:
    enabled: true
  teleport:
    enabled: true
  time:
    enabled: true
  uptime:
    enabled: true