Modules:
  Broadcast:
    Enabled: true
  ClearInventory:
    Enabled: true
  Coordinates:
    Enabled: true
  CrossTeleport:
    Enabled: true
  Fly:
    Enabled: true
  GameMode:
    Enabled: true
  Hat:
    Enabled: true
  Knockback:
    Enabled: true
  Lightning:
    Enabled: true
  PluginList:
    Enabled: true
    PluginPerPage: 10
  Rotate:
    Enabled: true
  Shuffle:
    Enabled: true
  Spawn:
    Enabled: true
    onJoin: true
    onRespawn: true
    onVoid: true
    location: ''
  Speed:
    Enabled: true
  Sudo:
    Enabled: true
  Teleport:
    Enabled: true
  Tell:
    Enabled: true