modules:
  broadcast:
    enabled: true
  clear_inventory:
    enabled: true
  coordinates:
    enabled: true
  cross_teleport:
    enabled: true
  feed:
    enabled: true
  fly:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  kill:
    enabled: true
  knockback:
    enabled: true
  lightning:
    enabled: true
  messages:
    join: true
    quit: true
  plugin_list:
    enabled: true
  private_chat:
    enabled: true
  rotate:
    enabled: true
  shuffle:
    enabled: true
  spawn:
    enabled: true
    on_join: true
    on_void: true
    on_respawn: true
    location: ''
  speed:
    enabled: true
  sudo:
    enabled: true
  teleport:
    enabled: true
  time:
    enabled: true
  uptime:
    enabled: true