name: Mercury
version: '${project.version}'
main: ir.ciph3r.mercury.Mercury
api-version: 1.13
authors: [ Ciph3r ]
softdepend: [SuperVanish, PremiumVanish]
description: A core plugin made to make life easier

commands:
  mercury:
    usage: /<command>
  broadcast:
    usage: /<command>
  clearinventory:
    usage: /<command>
    aliases: [ci]
  coordinates:
    usage: /<command>
    aliases: [coords]
  crossteleport:
    usage: /<command>
    aliases: [crosstp, ctp]
  feed:
    usage: /<command>
  fly:
    usage: /<command>
  gamemode:
    usage: /<command>
    aliases: [gmc, gms, gma, gmsp]
  hat:
    usage: /<command>
  Heal:
    usage: /<command>
  knockback:
    usage: /<command>
    aliases: [knock]
  lightning:
    usage: /<command>
  pluginlist:
    usage: /<command>
  rotate:
    usage: /<command>
  shuffle:
    usage: /<command>
  spawn:
    usage: /<command>
  setspawn:
    usage: /<command>
  Speed:
    usage: /<command>
  sudo:
    usage: /<command>
  teleport:
    usage: /<command>
    aliases: [tp]
  tell:
    usage: /<command>
    aliases: [t, message, msg, whisper]
  reply:
    usage: /<command>
    aliases: [r]