name: Mercury
version: '${version}'
main: ir.ciph3r.mercury.Mercury
api-version: 1.13
authors: [ Ciph3r ]
softdepend: [ SuperVanish, PremiumVanish, PlaceholderAPI ]
description: A server core plugin made to make life easier.
