name: Mercury
version: '${project.version}'
main: ir.ciph3r.mercury.Mercury
api-version: 1.13
authors: [ Ciph3r ]
softdepend: [SuperVanish, PremiumVanish]
description: A core plugin made to make life easier

commands:
  mercury:
    usage: /<command>
  fly:
    usage: /<command>
  gamemode:
    usage: /<command>
    aliases: [gmc, gms, gma, gmsp]
  teleport:
    usage: /<command>
    aliases: [tp]
  hat:
    usage: /<command>
  shuffle:
    usage: /<command>
  rotate:
    usage: /<command>
  knockback:
    usage: /<command>
  clearinventory:
    usage: /<command>
    aliases: [ci]
  Speed:
    usage: /<command>
  tell:
    usage: /<command>
    aliases: [t]
  reply:
    usage: /<command>
    aliases: [r]
  crossteleport:
    usage: /<command>
    aliases: [crosstp, ctp]
  sudo:
    usage: /<command>
  spawn:
    usage: /<command>
  setspawn:
    usage: /<command>
  lightning:
    usage: /<command>
  Coordinates:
    usage: /<command>
    aliases: [coords]